import { homeDataProps } from "@/types/homeDataTypes";
import nurseAssistantIcon from "@/assets/icons/nurse-assistant.svg";
import profileIcon from "@/assets/icons/profile.svg";
import boxIcon from "@/assets/icons/box.svg";
import peopleIcon from "@/assets/icons/people.svg";
import profileCardIcon from "@/assets/icons/profile-card.svg";
import cardIcon from "@/assets/icons/card.svg";
import moneyIcon from "@/assets/icons/money.svg";
import dataIcon from "@/assets/icons/data2.svg";
import shieldSecurityIcon from "@/assets/icons/shield-security.svg";

export const homeDatas: homeDataProps[] = [
  {
    title: "Nursing Assistant - Healthcare Specialist",
    route: "nursing-assistant",
    icon: nurseAssistantIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "250",
    active: "140",
    liquidated: "110",
    tableData: [
      {
        customerName: "Miles, Esther",
        customerNumber: "20067754632",
        customerCateory: "Individual",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
      {
        customerName: "James, Esther",
        customerNumber: "20067754632",
        customerCateory: "Corporate",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
      {
        customerName: "Rodriguez, Carlos",
        customerNumber: "20073845621",
        customerCateory: "Individual",
        principal: "NGN 15,500.00",
        userAliasTopData: "purplelion555",
        userAliasBottomData: "greentiger127",
        status: "Active",
        lastUpdated: "Mar 12, 2022",
      },
      {
        customerName: "Smith, Emily",
        customerNumber: "20088976541",
        customerCateory: "Corporate",
        principal: "NGN 22,750.00",
        userAliasTopData: "redpanda432",
        userAliasBottomData: "bluefox189",
        status: "Liquidated",
        lastUpdated: "Apr 03, 2022",
      },
      {
        customerName: "Johnson, Michael",
        customerNumber: "20099287436",
        customerCateory: "Individual",
        principal: "NGN 8,200.00",
        userAliasTopData: "yellowmonkey762",
        userAliasBottomData: "blackcat341",
        status: "Active",
        lastUpdated: "Feb 15, 2022",
      },
      {
        customerName: "Williams, David",
        customerNumber: "20103456789",
        customerCateory: "Corporate",
        principal: "NGN 17,900.00",
        userAliasTopData: "silverfish629",
        userAliasBottomData: "goldwolf228",
        status: "Liquidated",
        lastUpdated: "May 22, 2022",
      },
      {
        customerName: "Thompson, Jessica",
        customerNumber: "20115634218",
        customerCateory: "Individual",
        principal: "NGN 11,350.00",
        userAliasTopData: "greeneagle103",
        userAliasBottomData: "purplehorse415",
        status: "Active",
        lastUpdated: "Jun 08, 2022",
      },
      {
        customerName: "Garcia, Anna",
        customerNumber: "20127834560",
        customerCateory: "Individual",
        principal: "NGN 9,750.00",
        userAliasTopData: "orangebear778",
        userAliasBottomData: "bluebird621",
        status: "Active",
        lastUpdated: "Jul 17, 2022",
      },
      {
        customerName: "Martinez, Roberto",
        customerNumber: "20134539870",
        customerCateory: "Corporate",
        principal: "NGN 14,600.00",
        userAliasTopData: "redsnake109",
        userAliasBottomData: "whiteelephant332",
        status: "Liquidated",
        lastUpdated: "Aug 29, 2022",
      },
      {
        customerName: "Brown, Christopher",
        customerNumber: "20143267891",
        customerCateory: "Individual",
        principal: "NGN 12,800.00",
        userAliasTopData: "blackbear441",
        userAliasBottomData: "greenfrog276",
        status: "Active",
        lastUpdated: "Sep 14, 2022",
      },
      {
        customerName: "Davis, Michelle",
        customerNumber: "20159087642",
        customerCateory: "Corporate",
        principal: "NGN 19,200.00",
        userAliasTopData: "purpledragon123",
        userAliasBottomData: "yellowtiger876",
        status: "Active",
        lastUpdated: "Oct 05, 2022",
      },
      {
        customerName: "Wilson, Thomas",
        customerNumber: "20167453928",
        customerCateory: "Individual",
        principal: "NGN 7,500.00",
        userAliasTopData: "blueelephant654",
        userAliasBottomData: "redlion987",
        status: "Liquidated",
        lastUpdated: "Nov 20, 2022",
      },
    ],
  },
  {
    title: "Profile Manager",
    route: "profile-manager",
    icon: profileIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "150",
    active: "70",
    liquidated: "80",
    tableData: [
      {
        customerName: "Black, Marvin",
        customerNumber: "20124487654",
        customerCateory: "Corporate",
        principal: "NGN 15,000.00",
        userAliasTopData: "orangefox902",
        userAliasBottomData: "greenlion718",
        status: "Liquidated",
        lastUpdated: "Feb 10, 2023",
      },
      {
        customerName: "Taylor, Sophia",
        customerNumber: "20189065432",
        customerCateory: "Individual",
        principal: "NGN 12,450.00",
        userAliasTopData: "purplewolf218",
        userAliasBottomData: "greentiger554",
        status: "Active",
        lastUpdated: "Mar 05, 2023",
      },
      {
        customerName: "Anderson, William",
        customerNumber: "20197834562",
        customerCateory: "Corporate",
        principal: "NGN 21,800.00",
        userAliasTopData: "redbear771",
        userAliasBottomData: "yellowfox123",
        status: "Liquidated",
        lastUpdated: "Apr 17, 2023",
      },
      {
        customerName: "Wong, Lisa",
        customerNumber: "20201234567",
        customerCateory: "Individual",
        principal: "NGN 9,600.00",
        userAliasTopData: "blackpanther435",
        userAliasBottomData: "silverfish219",
        status: "Active",
        lastUpdated: "May 22, 2023",
      },
      {
        customerName: "Clark, Daniel",
        customerNumber: "20219876543",
        customerCateory: "Corporate",
        principal: "NGN 18,750.00",
        userAliasTopData: "bluemonkey624",
        userAliasBottomData: "redsnake387",
        status: "Liquidated",
        lastUpdated: "Jun 09, 2023",
      },
      {
        customerName: "Lewis, Rachel",
        customerNumber: "20224561237",
        customerCateory: "Individual",
        principal: "NGN 11,200.00",
        userAliasTopData: "goldfish529",
        userAliasBottomData: "purplecat812",
        status: "Active",
        lastUpdated: "Jul 14, 2023",
      },
      {
        customerName: "Allen, Jeffrey",
        customerNumber: "20237654321",
        customerCateory: "Corporate",
        principal: "NGN 16,900.00",
        userAliasTopData: "whitebear176",
        userAliasBottomData: "blacktiger343",
        status: "Liquidated",
        lastUpdated: "Aug 03, 2023",
      },
      {
        customerName: "Young, Katherine",
        customerNumber: "20243217658",
        customerCateory: "Individual",
        principal: "NGN 10,300.00",
        userAliasTopData: "greenlion415",
        userAliasBottomData: "orangeelephant729",
        status: "Active",
        lastUpdated: "Sep 19, 2023",
      },
      {
        customerName: "Harris, Brandon",
        customerNumber: "20258765432",
        customerCateory: "Corporate",
        principal: "NGN 23,500.00",
        userAliasTopData: "redpanda633",
        userAliasBottomData: "bluefrog291",
        status: "Liquidated",
        lastUpdated: "Oct 25, 2023",
      },
      {
        customerName: "King, Olivia",
        customerNumber: "20267456321",
        customerCateory: "Individual",
        principal: "NGN 8,700.00",
        userAliasTopData: "yellowdragon847",
        userAliasBottomData: "purpleeagle562",
        status: "Active",
        lastUpdated: "Nov 11, 2023",
      },
      {
        customerName: "Wright, Alexander",
        customerNumber: "20278901234",
        customerCateory: "Corporate",
        principal: "NGN 19,850.00",
        userAliasTopData: "silvermonkey938",
        userAliasBottomData: "blackwolf176",
        status: "Liquidated",
        lastUpdated: "Dec 07, 2023",
      },
    ],
  },
  {
    title: "Creative Web Designer",
    route: "creative-web-designer",
    icon: boxIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "200",
    active: "80",
    liquidated: "120",
    tableData: [
      {
        customerName: "Thomas, Sarah",
        customerNumber: "20013456789",
        customerCateory: "Individual",
        principal: "NGN 8,500.00",
        userAliasTopData: "redtiger312",
        userAliasBottomData: "purpleowl129",
        status: "Active",
        lastUpdated: "Mar 15, 2023",
      },
      {
        customerName: "Scott, Andrew",
        customerNumber: "20281234567",
        customerCateory: "Corporate",
        principal: "NGN 17,350.00",
        userAliasTopData: "bluedragon425",
        userAliasBottomData: "redpanda178",
        status: "Liquidated",
        lastUpdated: "Jan 13, 2023",
      },
      {
        customerName: "Turner, Rebecca",
        customerNumber: "20294567890",
        customerCateory: "Individual",
        principal: "NGN 10,950.00",
        userAliasTopData: "greensnake632",
        userAliasBottomData: "yellowbear947",
        status: "Active",
        lastUpdated: "Feb 28, 2023",
      },
      {
        customerName: "Cooper, Ryan",
        customerNumber: "20307654321",
        customerCateory: "Corporate",
        principal: "NGN 24,700.00",
        userAliasTopData: "purplemonkey314",
        userAliasBottomData: "blackcat759",
        status: "Liquidated",
        lastUpdated: "Apr 06, 2023",
      },
      {
        customerName: "Murphy, Victoria",
        customerNumber: "20312345678",
        customerCateory: "Individual",
        principal: "NGN 9,250.00",
        userAliasTopData: "whitefox542",
        userAliasBottomData: "bluetiger836",
        status: "Active",
        lastUpdated: "May 19, 2023",
      },
      {
        customerName: "Howard, Jonathan",
        customerNumber: "20329876543",
        customerCateory: "Corporate",
        principal: "NGN 16,800.00",
        userAliasTopData: "silverfish219",
        userAliasBottomData: "greenlion654",
        status: "Liquidated",
        lastUpdated: "Jun 25, 2023",
      },
      {
        customerName: "Russell, Amanda",
        customerNumber: "20336789012",
        customerCateory: "Individual",
        principal: "NGN 11,650.00",
        userAliasTopData: "yellowwolf483",
        userAliasBottomData: "redmonkey926",
        status: "Active",
        lastUpdated: "Jul 10, 2023",
      },
      {
        customerName: "Gray, Matthew",
        customerNumber: "20341098765",
        customerCateory: "Corporate",
        principal: "NGN 20,900.00",
        userAliasTopData: "orangeelephant321",
        userAliasBottomData: "purpleswan764",
        status: "Liquidated",
        lastUpdated: "Aug 17, 2023",
      },
      {
        customerName: "Castro, Nicole",
        customerNumber: "20359876543",
        customerCateory: "Individual",
        principal: "NGN 7,800.00",
        userAliasTopData: "blacklion183",
        userAliasBottomData: "goldfrog527",
        status: "Active",
        lastUpdated: "Sep 04, 2023",
      },
      {
        customerName: "Wells, Richard",
        customerNumber: "20368765432",
        customerCateory: "Corporate",
        principal: "NGN 18,350.00",
        userAliasTopData: "bluebear495",
        userAliasBottomData: "greendragon138",
        status: "Liquidated",
        lastUpdated: "Oct 12, 2023",
      },
      {
        customerName: "Ward, Lauren",
        customerNumber: "20373456789",
        customerCateory: "Individual",
        principal: "NGN 13,200.00",
        userAliasTopData: "redfish746",
        userAliasBottomData: "whitepanther259",
        status: "Active",
        lastUpdated: "Nov 29, 2023",
      },
    ],
  },
  {
    title: "Certified Dog Trainer",
    route: "certified-dog-trainer",
    icon: peopleIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "230",
    active: "110",
    liquidated: "120",
    tableData: [
      {
        customerName: "Johnson, Peter",
        customerNumber: "20987654321",
        customerCateory: "Corporate",
        principal: "NGN 20,000.00",
        userAliasTopData: "blackeagle441",
        userAliasBottomData: "yellowwhale777",
        status: "Liquidated",
        lastUpdated: "Apr 03, 2024",
      },
      {
        customerName: "Foster, Brian",
        customerNumber: "20389012345",
        customerCateory: "Individual",
        principal: "NGN 12,750.00",
        userAliasTopData: "silverpanda276",
        userAliasBottomData: "redowl538",
        status: "Active",
        lastUpdated: "Jan 07, 2024",
      },
      {
        customerName: "Coleman, Melissa",
        customerNumber: "20396543210",
        customerCateory: "Corporate",
        principal: "NGN 22,900.00",
        userAliasTopData: "greentiger824",
        userAliasBottomData: "bluemonkey167",
        status: "Liquidated",
        lastUpdated: "Feb 15, 2024",
      },
      {
        customerName: "Jenkins, Tyler",
        customerNumber: "20407654321",
        customerCateory: "Individual",
        principal: "NGN 9,850.00",
        userAliasTopData: "purpleelephant492",
        userAliasBottomData: "yellowfox713",
        status: "Active",
        lastUpdated: "Mar 22, 2024",
      },
      {
        customerName: "Rivera, Stephanie",
        customerNumber: "20418765432",
        customerCateory: "Corporate",
        principal: "NGN 17,250.00",
        userAliasTopData: "blackfish865",
        userAliasBottomData: "whitedragon239",
        status: "Liquidated",
        lastUpdated: "Apr 30, 2024",
      },
      {
        customerName: "Butler, Jason",
        customerNumber: "20429876543",
        customerCateory: "Individual",
        principal: "NGN 11,400.00",
        userAliasTopData: "orangelion357",
        userAliasBottomData: "greenbear642",
        status: "Active",
        lastUpdated: "May 18, 2024",
      },
      {
        customerName: "Barnes, Samantha",
        customerNumber: "20431234567",
        customerCateory: "Corporate",
        principal: "NGN 19,800.00",
        userAliasTopData: "redfrog194",
        userAliasBottomData: "purpletiger528",
        status: "Liquidated",
        lastUpdated: "Jun 05, 2024",
      },
      {
        customerName: "Rogers, William",
        customerNumber: "20445678901",
        customerCateory: "Individual",
        principal: "NGN 8,350.00",
        userAliasTopData: "bluesnake673",
        userAliasBottomData: "blackpanda416",
        status: "Active",
        lastUpdated: "Jul 13, 2024",
      },
      {
        customerName: "Reed, Christina",
        customerNumber: "20452345678",
        customerCateory: "Corporate",
        principal: "NGN 25,600.00",
        userAliasTopData: "silvermonkey291",
        userAliasBottomData: "yellowwolf834",
        status: "Liquidated",
        lastUpdated: "Aug 21, 2024",
      },
      {
        customerName: "Morgan, Daniel",
        customerNumber: "20467890123",
        customerCateory: "Individual",
        principal: "NGN 14,250.00",
        userAliasTopData: "goldcat957",
        userAliasBottomData: "greenelephant483",
        status: "Active",
        lastUpdated: "Sep 09, 2024",
      },
      {
        customerName: "Bell, Elizabeth",
        customerNumber: "20476543210",
        customerCateory: "Corporate",
        principal: "NGN 18,500.00",
        userAliasTopData: "purplefish327",
        userAliasBottomData: "redtiger749",
        status: "Liquidated",
        lastUpdated: "Oct 17, 2024",
      },
    ],
  },
  {
    title: "Nursing Assistant - Senior Care",
    route: "nursing-assistant",
    icon: profileCardIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "170",
    active: "120",
    liquidated: "50",
    tableData: [
      {
        customerName: "Hughes, Natalie",
        customerNumber: "20345678901",
        customerCateory: "Individual",
        principal: "NGN 9,200.00",
        userAliasTopData: "silverhawk299",
        userAliasBottomData: "bluemouse963",
        status: "Active",
        lastUpdated: "May 22, 2023",
      },
      {
        customerName: "Baker, Timothy",
        customerNumber: "20489012345",
        customerCateory: "Corporate",
        principal: "NGN 16,450.00",
        userAliasTopData: "whiteswan427",
        userAliasBottomData: "blackeagle185",
        status: "Liquidated",
        lastUpdated: "Jan 19, 2023",
      },
      {
        customerName: "Powell, Jennifer",
        customerNumber: "20498765432",
        customerCateory: "Individual",
        principal: "NGN 10,800.00",
        userAliasTopData: "bluelion639",
        userAliasBottomData: "redpanda214",
        status: "Active",
        lastUpdated: "Feb 26, 2023",
      },
      {
        customerName: "Long, Robert",
        customerNumber: "20501234567",
        customerCateory: "Corporate",
        principal: "NGN 23,700.00",
        userAliasTopData: "yellowsnake352",
        userAliasBottomData: "purplefox798",
        status: "Liquidated",
        lastUpdated: "Mar 14, 2023",
      },
      {
        customerName: "Perry, Stephanie",
        customerNumber: "20512345678",
        customerCateory: "Individual",
        principal: "NGN 8,950.00",
        userAliasTopData: "greendragon741",
        userAliasBottomData: "silverbear256",
        status: "Active",
        lastUpdated: "Apr 28, 2023",
      },
      {
        customerName: "Cook, Brandon",
        customerNumber: "20529876543",
        customerCateory: "Corporate",
        principal: "NGN 15,300.00",
        userAliasTopData: "orangecat163",
        userAliasBottomData: "bluetiger547",
        status: "Active",
        lastUpdated: "Jun 07, 2023",
      },
      {
        customerName: "Simmons, Laura",
        customerNumber: "20537654321",
        customerCateory: "Individual",
        principal: "NGN 11,750.00",
        userAliasTopData: "redmonkey625",
        userAliasBottomData: "whitewolf932",
        status: "Active",
        lastUpdated: "Jul 15, 2023",
      },
      {
        customerName: "Bennett, Gregory",
        customerNumber: "20541234567",
        customerCateory: "Corporate",
        principal: "NGN 21,400.00",
        userAliasTopData: "blackbear378",
        userAliasBottomData: "goldfish145",
        status: "Liquidated",
        lastUpdated: "Aug 23, 2023",
      },
      {
        customerName: "Wood, Megan",
        customerNumber: "20558901234",
        customerCateory: "Individual",
        principal: "NGN 9,650.00",
        userAliasTopData: "purpleowl581",
        userAliasBottomData: "greenpanda429",
        status: "Active",
        lastUpdated: "Sep 30, 2023",
      },
      {
        customerName: "Fisher, Christopher",
        customerNumber: "20567890123",
        customerCateory: "Corporate",
        principal: "NGN 18,900.00",
        userAliasTopData: "yellowelephant762",
        userAliasBottomData: "redsnake314",
        status: "Active",
        lastUpdated: "Oct 11, 2023",
      },
      {
        customerName: "Ross, Victoria",
        customerNumber: "20574321098",
        customerCateory: "Individual",
        principal: "NGN 13,250.00",
        userAliasTopData: "bluetiger493",
        userAliasBottomData: "silvermonkey851",
        status: "Active",
        lastUpdated: "Nov 02, 2023",
      },
    ],
  },
  {
    title: "Marketing Coordinator - Brand Growth",
    route: "marketing-coordinator",
    icon: cardIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "190",
    active: "120",
    liquidated: "70",
    tableData: [
      {
        customerName: "Walker, Julia",
        customerNumber: "20754321987",
        customerCateory: "Corporate",
        principal: "NGN 11,500.00",
        userAliasTopData: "goldfox144",
        userAliasBottomData: "redshark662",
        status: "Liquidated",
        lastUpdated: "Nov 10, 2023",
      },
      {
        customerName: "Ellis, Nathan",
        customerNumber: "20589012345",
        customerCateory: "Individual",
        principal: "NGN 12,950.00",
        userAliasTopData: "blacklion247",
        userAliasBottomData: "orangefrog682",
        status: "Active",
        lastUpdated: "Jan 05, 2023",
      },
      {
        customerName: "Harrison, Olivia",
        customerNumber: "20594567890",
        customerCateory: "Corporate",
        principal: "NGN 19,750.00",
        userAliasTopData: "whitepanda415",
        userAliasBottomData: "purplefish368",
        status: "Liquidated",
        lastUpdated: "Feb 18, 2023",
      },
      {
        customerName: "Grant, Thomas",
        customerNumber: "20607654321",
        customerCateory: "Individual",
        principal: "NGN 9,300.00",
        userAliasTopData: "greeneagle593",
        userAliasBottomData: "bluecat127",
        status: "Active",
        lastUpdated: "Mar 26, 2023",
      },
      {
        customerName: "Wallace, Stephanie",
        customerNumber: "20612345678",
        customerCateory: "Corporate",
        principal: "NGN 24,800.00",
        userAliasTopData: "silverwolf731",
        userAliasBottomData: "reddragon209",
        status: "Liquidated",
        lastUpdated: "Apr 14, 2023",
      },
      {
        customerName: "Mason, Andrew",
        customerNumber: "20623456789",
        customerCateory: "Individual",
        principal: "NGN 10,600.00",
        userAliasTopData: "yellowtiger876",
        userAliasBottomData: "blackbear542",
        status: "Active",
        lastUpdated: "May 27, 2023",
      },
      {
        customerName: "Dixon, Rachel",
        customerNumber: "20639876543",
        customerCateory: "Corporate",
        principal: "NGN 17,900.00",
        userAliasTopData: "bluemonkey385",
        userAliasBottomData: "greenelephant619",
        status: "Active",
        lastUpdated: "Jun 09, 2023",
      },
      {
        customerName: "Warren, Daniel",
        customerNumber: "20647654321",
        customerCateory: "Individual",
        principal: "NGN 8,750.00",
        userAliasTopData: "purpledragon142",
        userAliasBottomData: "orangepanda753",
        status: "Liquidated",
        lastUpdated: "Jul 21, 2023",
      },
      {
        customerName: "Ferguson, Sarah",
        customerNumber: "20651234567",
        customerCateory: "Corporate",
        principal: "NGN 15,350.00",
        userAliasTopData: "redfox416",
        userAliasBottomData: "whitetiger839",
        status: "Active",
        lastUpdated: "Aug 08, 2023",
      },
      {
        customerName: "Owen, Matthew",
        customerNumber: "20668901234",
        customerCateory: "Individual",
        principal: "NGN 13,800.00",
        userAliasTopData: "blackfish274",
        userAliasBottomData: "goldlion527",
        status: "Active",
        lastUpdated: "Sep 16, 2023",
      },
      {
        customerName: "Mills, Jessica",
        customerNumber: "20676543210",
        customerCateory: "Corporate",
        principal: "NGN 22,100.00",
        userAliasTopData: "bluesnake691",
        userAliasBottomData: "silvercat348",
        status: "Liquidated",
        lastUpdated: "Oct 23, 2023",
      },
    ],
  },
  {
    title: "Medical Assistant",
    route: "medical-assistant",
    icon: shieldSecurityIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "135",
    active: "35",
    liquidated: "100",
    tableData: [
      {
        customerName: "Black, Marvin",
        customerNumber: "20124487654",
        customerCateory: "Corporate",
        principal: "NGN 15,000.00",
        userAliasTopData: "orangefox902",
        userAliasBottomData: "greenlion718",
        status: "Liquidated",
        lastUpdated: "Feb 10, 2023",
      },
      {
        customerName: "Taylor, Sophia",
        customerNumber: "20189065432",
        customerCateory: "Individual",
        principal: "NGN 12,450.00",
        userAliasTopData: "purplewolf218",
        userAliasBottomData: "greentiger554",
        status: "Active",
        lastUpdated: "Mar 05, 2023",
      },
      {
        customerName: "Anderson, William",
        customerNumber: "20197834562",
        customerCateory: "Corporate",
        principal: "NGN 21,800.00",
        userAliasTopData: "redbear771",
        userAliasBottomData: "yellowfox123",
        status: "Liquidated",
        lastUpdated: "Apr 17, 2023",
      },
      {
        customerName: "Wong, Lisa",
        customerNumber: "20201234567",
        customerCateory: "Individual",
        principal: "NGN 9,600.00",
        userAliasTopData: "blackpanther435",
        userAliasBottomData: "silverfish219",
        status: "Active",
        lastUpdated: "May 22, 2023",
      },
      {
        customerName: "Clark, Daniel",
        customerNumber: "20219876543",
        customerCateory: "Corporate",
        principal: "NGN 18,750.00",
        userAliasTopData: "bluemonkey624",
        userAliasBottomData: "redsnake387",
        status: "Liquidated",
        lastUpdated: "Jun 09, 2023",
      },
      {
        customerName: "Lewis, Rachel",
        customerNumber: "20224561237",
        customerCateory: "Individual",
        principal: "NGN 11,200.00",
        userAliasTopData: "goldfish529",
        userAliasBottomData: "purplecat812",
        status: "Active",
        lastUpdated: "Jul 14, 2023",
      },
      {
        customerName: "Allen, Jeffrey",
        customerNumber: "20237654321",
        customerCateory: "Corporate",
        principal: "NGN 16,900.00",
        userAliasTopData: "whitebear176",
        userAliasBottomData: "blacktiger343",
        status: "Liquidated",
        lastUpdated: "Aug 03, 2023",
      },
      {
        customerName: "Young, Katherine",
        customerNumber: "20243217658",
        customerCateory: "Individual",
        principal: "NGN 10,300.00",
        userAliasTopData: "greenlion415",
        userAliasBottomData: "orangeelephant729",
        status: "Active",
        lastUpdated: "Sep 19, 2023",
      },
      {
        customerName: "Harris, Brandon",
        customerNumber: "20258765432",
        customerCateory: "Corporate",
        principal: "NGN 23,500.00",
        userAliasTopData: "redpanda633",
        userAliasBottomData: "bluefrog291",
        status: "Liquidated",
        lastUpdated: "Oct 25, 2023",
      },
      {
        customerName: "King, Olivia",
        customerNumber: "20267456321",
        customerCateory: "Individual",
        principal: "NGN 8,700.00",
        userAliasTopData: "yellowdragon847",
        userAliasBottomData: "purpleeagle562",
        status: "Active",
        lastUpdated: "Nov 11, 2023",
      },
      {
        customerName: "Wright, Alexander",
        customerNumber: "20278901234",
        customerCateory: "Corporate",
        principal: "NGN 19,850.00",
        userAliasTopData: "silvermonkey938",
        userAliasBottomData: "blackwolf176",
        status: "Liquidated",
        lastUpdated: "Dec 07, 2023",
      },
    ],
  },
  {
    title: "Marketing Coordinator - Revenue Strategy",
    route: "marketing-coordinator",
    icon: moneyIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "135",
    active: "35",
    liquidated: "100",
    tableData: [
      {
        customerName: "Miles, Esther",
        customerNumber: "20067754632",
        customerCateory: "Individual",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
      {
        customerName: "James, Esther",
        customerNumber: "20067754632",
        customerCateory: "Corporate",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
      {
        customerName: "Rodriguez, Carlos",
        customerNumber: "20073845621",
        customerCateory: "Individual",
        principal: "NGN 15,500.00",
        userAliasTopData: "purplelion555",
        userAliasBottomData: "greentiger127",
        status: "Active",
        lastUpdated: "Mar 12, 2022",
      },
      {
        customerName: "Smith, Emily",
        customerNumber: "20088976541",
        customerCateory: "Corporate",
        principal: "NGN 22,750.00",
        userAliasTopData: "redpanda432",
        userAliasBottomData: "bluefox189",
        status: "Liquidated",
        lastUpdated: "Apr 03, 2022",
      },
      {
        customerName: "Johnson, Michael",
        customerNumber: "20099287436",
        customerCateory: "Individual",
        principal: "NGN 8,200.00",
        userAliasTopData: "yellowmonkey762",
        userAliasBottomData: "blackcat341",
        status: "Active",
        lastUpdated: "Feb 15, 2022",
      },
      {
        customerName: "Williams, David",
        customerNumber: "20103456789",
        customerCateory: "Corporate",
        principal: "NGN 17,900.00",
        userAliasTopData: "silverfish629",
        userAliasBottomData: "goldwolf228",
        status: "Liquidated",
        lastUpdated: "May 22, 2022",
      },
      {
        customerName: "Thompson, Jessica",
        customerNumber: "20115634218",
        customerCateory: "Individual",
        principal: "NGN 11,350.00",
        userAliasTopData: "greeneagle103",
        userAliasBottomData: "purplehorse415",
        status: "Active",
        lastUpdated: "Jun 08, 2022",
      },
      {
        customerName: "Garcia, Anna",
        customerNumber: "20127834560",
        customerCateory: "Individual",
        principal: "NGN 9,750.00",
        userAliasTopData: "orangebear778",
        userAliasBottomData: "bluebird621",
        status: "Active",
        lastUpdated: "Jul 17, 2022",
      },
      {
        customerName: "Martinez, Roberto",
        customerNumber: "20134539870",
        customerCateory: "Corporate",
        principal: "NGN 14,600.00",
        userAliasTopData: "redsnake109",
        userAliasBottomData: "whiteelephant332",
        status: "Liquidated",
        lastUpdated: "Aug 29, 2022",
      },
      {
        customerName: "Brown, Christopher",
        customerNumber: "20143267891",
        customerCateory: "Individual",
        principal: "NGN 12,800.00",
        userAliasTopData: "blackbear441",
        userAliasBottomData: "greenfrog276",
        status: "Active",
        lastUpdated: "Sep 14, 2022",
      },
      {
        customerName: "Davis, Michelle",
        customerNumber: "20159087642",
        customerCateory: "Corporate",
        principal: "NGN 19,200.00",
        userAliasTopData: "purpledragon123",
        userAliasBottomData: "yellowtiger876",
        status: "Active",
        lastUpdated: "Oct 05, 2022",
      },
      {
        customerName: "Wilson, Thomas",
        customerNumber: "20167453928",
        customerCateory: "Individual",
        principal: "NGN 7,500.00",
        userAliasTopData: "blueelephant654",
        userAliasBottomData: "redlion987",
        status: "Liquidated",
        lastUpdated: "Nov 20, 2022",
      },
    ],
  },
  {
    title: "Web Developer",
    route: "web-developer",
    icon: dataIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "135",
    active: "35",
    liquidated: "100",
    tableData: [
      {
        customerName: "Johnson, Peter",
        customerNumber: "20987654321",
        customerCateory: "Corporate",
        principal: "NGN 20,000.00",
        userAliasTopData: "blackeagle441",
        userAliasBottomData: "yellowwhale777",
        status: "Liquidated",
        lastUpdated: "Apr 03, 2024",
      },
      {
        customerName: "Foster, Brian",
        customerNumber: "20389012345",
        customerCateory: "Individual",
        principal: "NGN 12,750.00",
        userAliasTopData: "silverpanda276",
        userAliasBottomData: "redowl538",
        status: "Active",
        lastUpdated: "Jan 07, 2024",
      },
      {
        customerName: "Coleman, Melissa",
        customerNumber: "20396543210",
        customerCateory: "Corporate",
        principal: "NGN 22,900.00",
        userAliasTopData: "greentiger824",
        userAliasBottomData: "bluemonkey167",
        status: "Liquidated",
        lastUpdated: "Feb 15, 2024",
      },
      {
        customerName: "Jenkins, Tyler",
        customerNumber: "20407654321",
        customerCateory: "Individual",
        principal: "NGN 9,850.00",
        userAliasTopData: "purpleelephant492",
        userAliasBottomData: "yellowfox713",
        status: "Active",
        lastUpdated: "Mar 22, 2024",
      },
      {
        customerName: "Rivera, Stephanie",
        customerNumber: "20418765432",
        customerCateory: "Corporate",
        principal: "NGN 17,250.00",
        userAliasTopData: "blackfish865",
        userAliasBottomData: "whitedragon239",
        status: "Liquidated",
        lastUpdated: "Apr 30, 2024",
      },
      {
        customerName: "Butler, Jason",
        customerNumber: "20429876543",
        customerCateory: "Individual",
        principal: "NGN 11,400.00",
        userAliasTopData: "orangelion357",
        userAliasBottomData: "greenbear642",
        status: "Active",
        lastUpdated: "May 18, 2024",
      },
      {
        customerName: "Barnes, Samantha",
        customerNumber: "20431234567",
        customerCateory: "Corporate",
        principal: "NGN 19,800.00",
        userAliasTopData: "redfrog194",
        userAliasBottomData: "purpletiger528",
        status: "Liquidated",
        lastUpdated: "Jun 05, 2024",
      },
      {
        customerName: "Rogers, William",
        customerNumber: "20445678901",
        customerCateory: "Individual",
        principal: "NGN 8,350.00",
        userAliasTopData: "bluesnake673",
        userAliasBottomData: "blackpanda416",
        status: "Active",
        lastUpdated: "Jul 13, 2024",
      },
      {
        customerName: "Reed, Christina",
        customerNumber: "20452345678",
        customerCateory: "Corporate",
        principal: "NGN 25,600.00",
        userAliasTopData: "silvermonkey291",
        userAliasBottomData: "yellowwolf834",
        status: "Liquidated",
        lastUpdated: "Aug 21, 2024",
      },
      {
        customerName: "Morgan, Daniel",
        customerNumber: "20467890123",
        customerCateory: "Individual",
        principal: "NGN 14,250.00",
        userAliasTopData: "goldcat957",
        userAliasBottomData: "greenelephant483",
        status: "Active",
        lastUpdated: "Sep 09, 2024",
      },
      {
        customerName: "Bell, Elizabeth",
        customerNumber: "20476543210",
        customerCateory: "Corporate",
        principal: "NGN 18,500.00",
        userAliasTopData: "purplefish327",
        userAliasBottomData: "redtiger749",
        status: "Liquidated",
        lastUpdated: "Oct 17, 2024",
      },
    ],
  },
];
