import { homeDataProps } from "@/types/homeDataTypes";
import nurseAssistantIcon from "@/assets/icons/nurse-assistant.svg";
import profileIcon from "@/assets/icons/profile.svg";
import boxIcon from "@/assets/icons/box.svg";
import peopleIcon from "@/assets/icons/people.svg";
import profileCardIcon from "@/assets/icons/profile-card.svg";
import cardIcon from "@/assets/icons/card.svg";
import moneyIcon from "@/assets/icons/money.svg";

export const homeDatas: homeDataProps[] = [
  {
    title: "Nursing Assistant - Healthcare Specialist",
    route: "nursing-assistant",
    icon: nurseAssistantIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "250",
    active: "140",
    liquidated: "110",
    tableData: [
      {
        customerName: "Miles, Esther",
        customerNumber: "20067754632",
        customerCateory: "Individual",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
      {
        customerName: "James, Esther",
        customerNumber: "20067754632",
        customerCateory: "Corporate",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
      {
        customerName: "James, Esther",
        customerNumber: "20067754632",
        customerCateory: "Corporate",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
      {
        customerName: "James, Esther",
        customerNumber: "20067754632",
        customerCateory: "Corporate",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
      {
        customerName: "James, Esther",
        customerNumber: "20067754632",
        customerCateory: "Corporate",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
      {
        customerName: "James, Esther",
        customerNumber: "20067754632",
        customerCateory: "Corporate",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
      {
        customerName: "James, Esther",
        customerNumber: "20067754632",
        customerCateory: "Corporate",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
      {
        customerName: "James, Esther",
        customerNumber: "20067754632",
        customerCateory: "Corporate",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
      {
        customerName: "James, Esther",
        customerNumber: "20067754632",
        customerCateory: "Corporate",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
      {
        customerName: "James, Esther",
        customerNumber: "20067754632",
        customerCateory: "Corporate",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
      {
        customerName: "James, Esther",
        customerNumber: "20067754632",
        customerCateory: "Corporate",
        principal: "NGN 10,000.00",
        userAliasTopData: "whiteswan331",
        userAliasBottomData: "bluebear234",
        status: "Active",
        lastUpdated: "Jan 24, 2022",
      },
    ],
  },
  {
    title: "Profile Manager",
    route: "profile-manager",
    icon: profileIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "150",
    active: "70",
    liquidated: "80",
    tableData: [
      {
        customerName: "Black, Marvin",
        customerNumber: "20124487654",
        customerCateory: "Corporate",
        principal: "NGN 15,000.00",
        userAliasTopData: "orangefox902",
        userAliasBottomData: "greenlion718",
        status: "Liquidated",
        lastUpdated: "Feb 10, 2023",
      },
    ],
  },
  {
    title: "Creative Web Designer",
    route: "creative-web-designer",
    icon: boxIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "200",
    active: "80",
    liquidated: "120",
    tableData: [
      {
        customerName: "Thomas, Sarah",
        customerNumber: "20013456789",
        customerCateory: "Individual",
        principal: "NGN 8,500.00",
        userAliasTopData: "redtiger312",
        userAliasBottomData: "purpleowl129",
        status: "Active",
        lastUpdated: "Mar 15, 2023",
      },
    ],
  },
  {
    title: "Certified Dog Trainer",
    route: "certified-dog-trainer",
    icon: peopleIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "230",
    active: "110",
    liquidated: "120",
    tableData: [
      {
        customerName: "Johnson, Peter",
        customerNumber: "20987654321",
        customerCateory: "Corporate",
        principal: "NGN 20,000.00",
        userAliasTopData: "blackeagle441",
        userAliasBottomData: "yellowwhale777",
        status: "Liquidated",
        lastUpdated: "Apr 03, 2024",
      },
    ],
  },
  {
    title: "Nursing Assistant - Senior Care",
    route: "nursing-assistant",
    icon: profileCardIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "170",
    active: "120",
    liquidated: "50",
    tableData: [
      {
        customerName: "Hughes, Natalie",
        customerNumber: "20345678901",
        customerCateory: "Individual",
        principal: "NGN 9,200.00",
        userAliasTopData: "silverhawk299",
        userAliasBottomData: "bluemouse963",
        status: "Active",
        lastUpdated: "May 22, 2023",
      },
    ],
  },
  {
    title: "Marketing Coordinator - Brand Growth",
    route: "marketing-coordinator",
    icon: cardIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "190",
    active: "120",
    liquidated: "70",
    tableData: [
      {
        customerName: "Walker, Julia",
        customerNumber: "20754321987",
        customerCateory: "Corporate",
        principal: "NGN 11,500.00",
        userAliasTopData: "goldfox144",
        userAliasBottomData: "redshark662",
        status: "Liquidated",
        lastUpdated: "Nov 10, 2023",
      },
    ],
  },
  {
    title: "Marketing Coordinator - Revenue Strategy",
    route: "marketing-coordinator",
    icon: moneyIcon,
    label:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
    all: "135",
    active: "35",
    liquidated: "100",
    tableData: [
      {
        customerName: "Nguyen, Alex",
        customerNumber: "20678905432",
        customerCateory: "Individual",
        principal: "NGN 12,300.00",
        userAliasTopData: "greenelephant407",
        userAliasBottomData: "orangepenguin348",
        status: "Active",
        lastUpdated: "Dec 18, 2023",
      },
    ],
  },
];
