import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideBar from "@/components/sidebar";
import Header from "@/components/header";
import { ConfigProvider } from "antd";
import { SearchProvider } from "@/context/SearchContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#A93636",
            },
          }}
        >
          <SearchProvider>
            <div className="flex h-screen">
              <SideBar />
              <div className="flex flex-col w-full">
                <Header />
                <div className="flex-1 overflow-y-auto">{children}</div>
              </div>
            </div>
          </SearchProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
